vn_name = "vn-for-linux"
vn_address = "10.0.0.0/16"
subnet_name = "public-subnet"
subnet_address = "10.0.2.0/24"
env = "UAT"
nsg_name= "network-for-linux"
vm_name = "vm-for-linux"
nic_name= "terraform-nic"